[project]
name = "cashier-server"
version = "0.13.0"
description = "Cashier synchronization server in Python"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "beancount>=3.2.0",
    "beanquery>=0.2.0",
    "fastapi>=0.135.1",
    "fava",
    "loguru>=0.7.3",
    "python-dotenv>=1.2.2",
    "uvicorn>=0.42.0",
    "beancount-lazy-plugins",
    "beancount-share",
    "beancount-interpolate",
    "beancount-reds-plugins",
]

[tool.uv.sources]
fava = { url = "https://github.com/Evernight/fava/raw/ee5aa0889bdde24204be2279ab14d50df71494c3/prebuilt_wheels/fava-1.30.13.dev23+gb4ccd7002.tar.gz" }
beancount-lazy-plugins = { git = "https://github.com/Evernight/beancount-lazy-plugins.git", rev = "28e1dd1eb54038eb9e610036cc96a510f81bbde1" }
beancount-share = { git = "https://github.com/Akuukis/beancount_share.git", rev = "4101c45e16948c0683520cebcf88afe4862224c4" }
beancount-interpolate = { git = "https://github.com/Akuukis/beancount_interpolate.git", rev = "e9c1241d5980781d270a7cc5c17cf2ca99c10faa" }
beancount-reds-plugins = { git = "https://github.com/redstreet/beancount_reds_plugins.git", rev = "41af12d13c6ba5b2949b2939dfa180f43a5cb307" }

[project.scripts]
cashier-server = "main:main"

[dependency-groups]
dev = [
    "pytest>=9.0.2",
    "pytest-asyncio>=1.3.0",
    "pytest-timeout>=2.3.1",
    "httpx>=0.28.0",
]

[tool.pytest.ini_options]
# pythonpath = [
#   "."
# ]
asyncio_default_fixture_loop_scope = "function"
markers = [
    "docker_acceptance: tests that require Docker daemon and a built image",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
# Include the package subfolder in the distribution package.
#packages = ["pricedl"]
only-include = ["main.py"]
